### ISSUE TITLE
RViz crashes after launching mc_rtc_ticker display.launch 

### ISSUE THREAD

**Issue by xeroxx** [jrl-umi3218/lipm_walking_controller#13]
Hi @arntanguy and @stephane-caron 
I went through the installation process described [here](https://jrl-umi3218.github.io/lipm_walking_controller/doxygen/HEAD/build.html). I've built and installed the dependencies like mc_rtc and etc., successfully. The problem is that after I run this command RViz crashes and I even couldn't find the rviz log file in the specifically mentioned log directory:

`roslaunch mc_rtc_ticker display.launch`
logfiles:
[installation_log_mc_rtc_edited.txt](https://github.com/jrl-umi3218/lipm_walking_controller/files/4051838/installation_log_mc_rtc_edited.txt)
[master.log](https://github.com/jrl-umi3218/lipm_walking_controller/files/4051829/master.log)
[roslaunch-hmr-ThinkPad-P1-26022.log](https://github.com/jrl-umi3218/lipm_walking_controller/files/4051831/roslaunch-hmr-ThinkPad-P1-26022.log)

My ~/.config/mc_rtc/mc_rtc.yaml file contains:
MainRobot: JVRC1
Enabled: LIPMWalking

and ~/.config/mc_rtc/mc_rtc.conf contains:
{
  "MainRobot": "JVRC1",
  "Enabled": ["LIPMWalking"]
}

**TERMINAL OUTPUT:** after running roslaunch command:
... logging to /home/saeed/.ros/log/c688036c-359d-11ea-a44e-3c6aa7374b96/roslaunch-hmr-ThinkPad-P1-26022.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://hmr-ThinkPad-P1:34115/

SUMMARY

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [26032]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c688036c-359d-11ea-a44e-3c6aa7374b96
process[rosout-1]: started with pid [26045]
started core service [/rosout]
process[rviz-2]: started with pid [26055]
[ INFO] [1578876235.187478565]: rviz version 1.12.17
[ INFO] [1578876235.187511420]: compiled against Qt version 5.5.1
[ INFO] [1578876235.187520824]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1578876235.264686350]: Stereo is NOT SUPPORTED
[ INFO] [1578876235.264738456]: OpenGl version: 3 (GLSL 1.3).
[rviz-2] process has died [pid 26055, exit code -11, cmd /opt/ros/kinetic/lib/rviz/rviz -d /home/saeed/repos/3rd_party/lipm/catkin_ws/src/mc_rtc_ros/mc_rtc_ticker/launch/display.rviz __name:=rviz __log:=/home/saeed/.ros/log/c688036c-359d-11ea-a44e-3c6aa7374b96/rviz-2.log].
log file: /home/saeed/.ros/log/c688036c-359d-11ea-a44e-3c6aa7374b96/rviz-2*.log

**Comment by gergondet** [comment]
Hi @xeroxx ,

I'm assuming you have no issue to run RViZ otherwise (i.e. `rosrun rviz rviz` is working correctly)

Otherwise, it seems you have mixed the binary installation with the source installation which might be creating some subtle problems, I suggest you either:
1. Remove the source installation of mc_rtc and mc_rtc_ros and try to run the controller from the binary installation;
2. Remove the binary installation, run build_and_install.sh again and try to run the controller again;

**Comment by xeroxx** [comment]
Yes, I don't have any problem to run RViz itself.
I actually already did your second suggestion (removed the binaries with apt-get remove) and after I run build_and_install and tried to run the controller again, I got those errors and RViz crashed.

**Comment by gergondet** [comment]
Ok, then the problem is most definitely on our side :)

Did you just run the opposite of the `sudo apt install` command you used? If so you might still have mc-rtc related packages lying around since some of those packages are meta-packages. You should be able (I think) to run `sudo apt autoremove` to remove the packages dragged by those meta-packages then check that you have no mc-rtc related packages installed (e.g. via `dpkg -l|grep mc-rtc`)

**Comment by xeroxx** [comment]
Thanks @gergondet, I tried `dpkg -l | grep mc-rtc` and there were some packages related to mc_rtc. I removed all those packages with `sudo apt autoremove`. After I ran `./build_and_install.sh` again, it installed everything successfully but still, I have the same issue.

**Comment by xeroxx** [comment]
Attached is the GDB output file of `roslaunch mc_rtc_ticker display.launch`
[gdb.txt](https://github.com/jrl-umi3218/lipm_walking_controller/files/4061858/gdb.txt)

**Comment by gergondet** [comment]
Hi @xeroxx, it looks like `/home/saeed/repos/3rd_party/lipm/catkin_ws/devel/lib//libmc_rtc_rviz_panel.so` is linked with Qt4 and not Qt5 which would explain the crash

Can you confirm:
- the output of `ldd /home/saeed/repos/3rd_party/lipm/catkin_ws/devel/lib//libmc_rtc_rviz_panel.so | grep -i qt` references Qt4 libraries
- you're running on Ubuntu 16.04 (Xenial)
- you have ROS kinetic installed
- `echo $ROS_DISTRO` gives `kinetic` in your shell

Normally, the only reason mc_rtc_rviz_panel would link to Qt4 is if `ROS_DISTRO` is `indigo`

If `ROS_DISTRO` is indeed `kinetic` then maybe you can get it to work by forcing catkin to rerun cmake: `cd /home/saeed/repos/3rd_party/lipm/catkin_ws && catkin_make --force-cmake` ?

**Comment by arntanguy** [comment]
Note that you can also set the environment variable `MC_RTC_RVIZ_PANEL_FORCE_QT5` to force `mc_rtc_rviz_panel` to build with Qt 5. This was initially intended so that one could force the use of Qt5 on systems with ros indigo (it would default to Qt 4 otherwise, as the default ubuntu trusty packages have rviz compiled with Qt 4).

**Comment by xeroxx** [comment]
Thanks @gergondet 

> Can you confirm:
> 
> * the output of `ldd /home/saeed/repos/3rd_party/lipm/catkin_ws/devel/lib//libmc_rtc_rviz_panel.so | grep -i qt` references Qt4 libraries

I get the same output even after I run `catkin_build --force-cmake`. The output was:

	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007feaadeba000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007feaad728000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007feaad252000)
	libQtSvg.so.4 => /usr/lib/x86_64-linux-gnu/libQtSvg.so.4 (0x00007feaa7f9a000)
	libQtOpenGL.so.4 => /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4 (0x00007feaa7c98000)
	libQtGui.so.4 => /usr/lib/x86_64-linux-gnu/libQtGui.so.4 (0x00007feaa6fa4000)
	libQtCore.so.4 => /usr/lib/x86_64-linux-gnu/libQtCore.so.4 (0x00007feaa6ab1000)

> * you're running on Ubuntu 16.04 (Xenial)

Yes. I'm running Ubuntu 16.04.6 LTS (4.15.0-74-generic)

> * you have ROS kinetic installed
> * `echo $ROS_DISTRO` gives `kinetic` in your shell

kinetic
 
> Normally, the only reason mc_rtc_rviz_panel would link to Qt4 is if `ROS_DISTRO` is `indigo`
> 
> If `ROS_DISTRO` is indeed `kinetic` then maybe you can get it to work by forcing catkin to rerun cmake: `cd /home/saeed/repos/3rd_party/lipm/catkin_ws && catkin_make --force-cmake` ?

I've done this. Then I did `catkin_make install`. I still have the same issue.

**Comment by xeroxx** [comment]
> Note that you can also set the environment variable `MC_RTC_RVIZ_PANEL_FORCE_QT5` to force `mc_rtc_rviz_panel` to build with Qt 5. This was initially intended so that one could force the use of Qt5 on systems with ros indigo (it would default to Qt 4 otherwise, as the default ubuntu trusty packages have rviz compiled with Qt 4).

Thanks, @arntanguy. I'm using ROS kinetic with Ubuntu 16.04.6.
I set `MC_RTC_RVIZ_PANEL_FORCE_QT5` to 1 and I built and installed it again, but I still have the same problem. You can see the ldd command output in the previous comment.

**Comment by gergondet** [comment]
I think I figured out the issue and it should be fixed by https://github.com/jrl-umi3218/mc_rtc_ros/commit/190126587eaaebcde04faaffda7658e0438a8678 (if there is Qwt packages installed for Qt4 and Qt5 then the previous behaviour would pick the Qt4 ones before)

Please git pull `mc_rtc_ros` and erase your catkin build and devel folders for this to kick in

Afterwards, you can confirm that Qt4 is not accidentally linked anymore and the plugin should work correctly.

**Comment by xeroxx** [comment]
Awesome, It worked very well. Thanks @gergondet!
